### PR TITLE
raise UnexpectedResponse when an error occurs

### LINKED ISSUE #113: Use UnexpectedResponse when trapping for errors from Globus to trigger token refresh
from sul-dlss/globus_client/issues/112#issuecomment-1730474211

We believe there is situation where we have a call not triggering the TokenWrapper refresh because it doesn't use the UnexpectedResponse. https://github.com/sul-dlss/globus_client/blob/main/lib/globus_client/endpoint.rb#L196-L198

The work of this ticket is to change /lib/globus_client/endpoint.rb#L202 to raise an UnexpectedResponse error, and then to bump the version of the gem and release the gem so it will be picked up in Monday's dependency updates.

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made? 🤔

Fixes #113 - use the `UnexpectedResponse` exception when an error occurs, so it can be correctly caught by the `TokenRefresh` logic.  Add in the ability to pass in a custom message for logging the exception too.

## How was this change tested? 🤨

Added a new spec

### CODE REVIEW

**Review by mjgiarlo — APPROVED** [review]

File: lib/globus_client/endpoint.rb [hunk 1]
```diff
@@ -199,7 +199,8 @@ def access_rule
 
       # debugging of Globus responses
       response_body = JSON.parse(response.body)
-      raise(StandardError, "Response is missing DATA in: #{response_body}") unless response_body.key?("DATA")
+
+      UnexpectedResponse.call(response, message: "Response is missing DATA in: #{response_body}") unless response.success? && response_body.key?("DATA")
```
Comment (ndushay) [inline lib/globus_client/endpoint.rb:203]: why call instead of raise?

Comment (peetucket) [reply lib/globus_client/endpoint.rb:203]: That class has a method called `#call` which examines the response and then raises different exceptions based on what is in the response.  It's a blanket wrapper for a bunch of logic about how to handle the different responses that come back.

Comment (peetucket) [reply lib/globus_client/endpoint.rb:203]: see https://github.com/sul-dlss/globus_client/blob/main/lib/globus_client/unexpected_response.rb#L29-L45

Comment (mjgiarlo) [reply lib/globus_client/endpoint.rb:203]: If we raise `StandardError` here, we short-circuit the ability to refresh the token on a 401. Using `UnexpectedResponse.call` will raise a more targeted custom exception, e.g., `UnauthorizedError`, which is what the `TokenWrapper` uses to detect the situation where a token needs to be refreshed.
